block.settings.page_url_qr_code_block:
  type: block_settings
  label: 'QR Code block configuration'
  mapping:
    page_url_qr_code_caption:
      type: text
      label: 'Caption'
      description: 'Will display under the QR Code'
    page_url_qr_code_alt:
      type: text
      label: 'Alt Text'
    page_url_qr_code_width_height:
      type: text
      label: 'QR Code Width & Height'
      description: 'Width & Height will be same. i.e. 150'
    page_url_qr_code_api:
      type: text
      label: 'Select API'
      description: 'Select other API where Google is restricted'