<?php

/**
 * @file
 * Contains md_aco_press.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function md_aco_press_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the md_aco_press module.
    case 'help.page.md_aco_press':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Description: actualites for homepage.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */

function md_aco_press_theme($existing, $type, $theme, $path)
{
  return array(
      'theme_md_aco_presss_page' => array(
          'variables' => array('nodes' => NULL,'cur_lang' => NULL),
          'template' => 'theme-md-press-page'
      ),
  );
}
