<?php

/**
 * @file
 * Contains md_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\md_block\Newsletter\Newsletter;

/**
 * Implements hook_help().
 */
function md_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the md_block module.
    case 'help.page.md_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Description: Slider for homepage.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */

function md_block_theme($existing, $type, $theme, $path)
{
  return array(
      'theme_md_block' => array(
          'variables' => array('md_block' => NULL),
          'template' => 'theme-md-block'
      ),
  );
}
