<?php

/**
 * @file
 * Contains md_mot_directeur.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
//use Drupal\md_slider\Newsletter\Newsletter;

/**
 * Implements hook_help().
 */
function md_mot_directeur_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the md_mot_directeur module.
    case 'help.page.md_mot_directeur':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Description: Mot du directeru en accueil.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */

function md_mot_directeur_theme($existing, $type, $theme, $path)
{
  return array(
      'theme_md_mot_directeur' => array(
          'variables' => array('mots' => NULL),
          'template' => 'theme-md-mot-directeur'
      ),
  );
}
