# Schema for fixed block content configuration entities.

fixed_block_content.fixed_block_content.*:
  type: config_entity
  label: 'Fixed block content'
  mapping:
    id:
      type: string
      label: 'ID'
    title:
      type: label
      label: 'Title'
    block_content_bundle:
      type: string
      label: 'Target custom block type'
    default_content:
      type: string
      label: 'Serialized default block content'
    auto_export:
      type: integer
      label: 'Option for the automatic export of default content on config update'
    protected:
      type: boolean
      label: 'The protected option'
