<?php

/**
 * @file
 * Contains md_appel_offre.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function md_appel_offre_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the md_appel_offre module.
    case 'help.page.md_appel_offre':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Description: appel offre for homepage.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */

function md_appel_offre_theme($existing, $type, $theme, $path)
{
  return array(
      'theme_md_appel_offre_hp' => array(
'variables' => ['nodes' => NULL ,'cur_lang' => NULL],
          'template' => 'theme-md-appel-offre-hp',

      ),
      'theme_md_appel_offre_page' => array(
          'variables' => ['nodes' => NULL],
          'template' => 'theme-md-appel-offre-page'
      ),
    'theme_tag' => [
      'variables' => ['my_variable' => NULL],
    ],
  );
}
