<?php

/**
 * @file
 * Main code for CKEditor Bootstrap Include module.
 */

/**
 * Implements hook_ckeditor_plugin().
 */
function ckeditor_bootstrap_include_ckeditor_plugin() {
  return array(
    'jsplusInclude' => array(
      'name' => 'jsplusInclude',
      'desc' => t('CKEditor Bootstrap Include. See <a href=":addon_page_url">@addon_page_title</a> for more details.',
        array(
          ':addon_page_url' => 'https://js.plus/products/include-css-js',
          '@addon_page_title' => t('addon page'),
        )),
      'path' => base_path() . 'libraries/jsplusInclude'
    ),
  );
}
