<?php

/**
 * @file
 * Contains md_ms.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function md_ms_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the md_ms module.
    case 'help.page.md_ms':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Description: actualites for homepage.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */

function md_ms_theme($existing, $type, $theme, $path)
{
  return array(
      'theme_md_ms_hp' => array(
          'variables' => array('nodes' => NULL,'cur_lang' => NULL,'ms_title'=> NULL,'ms_image'=> NULL ),
          'template' => 'theme-md-ms-hp'
      ),
      'theme_md_ns_hp' => array(
          'variables' => array('nodes' => NULL,'cur_lang' => NULL,'ns_title'=> NULL),
          'template' => 'theme-md-ns-hp'
      ),
      'theme_md_pub_hp' => array(
          'variables' => array('pub_link' => NULL,'cur_lang' => NULL),
          'template' => 'theme-md-pub-hp'
      ),
  );
}
