# Schema for the Better Exposed Filters Layout.
views.exposed_form.vefl_bef:
  type: views_exposed_form
  label: 'Better Exposed Filters (with layout)'
  mapping:
    input_required:
      type: boolean
      label: 'Input required before showing results'
    text_input_required:
      type: text
      label: 'Text shown if a filter option has not been selected'
    text_input_required_format:
      type: text
      label: 'Text format for the text_input_required field'
    bef:
      type: sequence
      label: 'BEF Settings'
      sequence:
        type: better_exposed_filters.[%key]
